---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check for Go Binary
      ansible.builtin.command: /usr/local/go/bin/go version
      register: test_go_binary
      changed_when: false

    - name: Test
      ansible.builtin.assert:
        that:
          - test_go_binary.rc == 0
