name: CI
on:
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "**.md"
      - "LICENSE"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow}}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    uses: trfore/ansible-role/.github/workflows/format.yml@main # remote repo

  lint_ansible:
    needs:
      - format
    uses: trfore/ansible-role/.github/workflows/lint_ansible.yml@main # remote repo

  test:
    needs:
      - format
      - lint_ansible
    strategy:
      fail-fast: false
      matrix:
        distro: [centos9, debian12, ubuntu2404]
        experimental: [false]
        molecule_scenario: ["-s default"]
    uses: trfore/ansible-role/.github/workflows/test_ansible.yml@main # remote repo
    with:
      distro: ${{ matrix.distro }}
      experimental: ${{ matrix.experimental }}
      molecule_scenario: ${{ matrix.molecule_scenario }}
      requirements_file: "requirements/dev-requirements.txt"

  check:
    if: ${{ always() }}
    needs:
      - format
      - lint_ansible
      - test
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.format.result }}',
          '${{ needs.lint_ansible.result }}',
          '${{ needs.test.result }}',
          ]) == {'success'}"
